import { useState, useEffect } from 'react';

const DEFAULT_THEME = {
  images: { heroLeft: '', heroRight: '', logo: '/logo.png', aboutHero: '', galleryBg: '', ogImage: '' },
  colors: { primary: '#7b1f24', background: '#f5f0eb', text: '#000000', accent: '#7b1f24' },
  fonts: { heading: 'Bebas Neue', body: 'Inter', mono: 'Space Mono' },
  texts: {
    siteTitle: 'Altered Venganza',
    subtitle: 'Multi-disciplinary studio made for brands that builds.',
    tagline: 'Premium branding • Custom designs • Pre-mades & softwares for fashion designers and creatives',
    location: 'Trieste, Italy / by Rare Martinez',
    premadeSubtitle1: 'Pre-made clothing renders • Production ready files',
    premadeSubtitle2: 'Fully alterable & customizable to your brand • Numbered & Ready to purchase',
  },
  instagram: { handle: 'alteredvenganza', hashtag: '#premade' },
  premadePrice: 200,
};

let cachedTheme = null;

export function useTheme() {
  const [theme, setTheme] = useState(cachedTheme || DEFAULT_THEME);

  useEffect(() => {
    if (cachedTheme) return;
    // Try to load theme.json (generated by admin)
    fetch('/data/theme.json')
      .then(r => r.ok ? r.json() : null)
      .then(data => {
        if (data) {
          const merged = { ...DEFAULT_THEME, ...data, images: { ...DEFAULT_THEME.images, ...data.images } };
          cachedTheme = merged;
          setTheme(merged);
        }
      })
      .catch(() => {}); // Use defaults if not found
  }, []);

  return theme;
}
